name = "DandelionWebSockets"
uuid = "a3dee88c-baf6-5d24-a1ed-2b752da90c9e"
authors = ["Erik Edin <erikedin@users.noreply.github.com>"]
version = "0.1.2"

[deps]
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Requests = "df88083b-ffd0-5ec9-9f27-0a3b3d809c9f"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
